package com.constants.components;

public interface AdminConstants extends ResponseMapConstants {
	
	String MESG_PROPERTY_FILE_NAME = "spring.components.admin";
	
	String SUPPORT_TEAM_REPORT = "SUPPORT_TEAM_REPORT";
	String ADMIN_REPORT = "ADMIN_REPORT";
	
	String USER_EMPLOYEE = "01";
	String USER_TUTOR = "02";
	String USER_CUSTOMER = "03";
	
	String COMPLAINT_STATUS_FRESH = "01";
	String COMPLAINT_STATUS_RESOLVED = "02";
	String COMPLAINT_STATUS_PUT_ON_HOLD = "03";
	
	// Message Constants
	String FAILURE_MESSAGE_THIS_CONTACT_NUMBER_ALREADY_EXISTS_IN_THE_SYSTEM = "FAILURE_MESSAGE_THIS_CONTACT_NUMBER_ALREADY_EXISTS_IN_THE_SYSTEM";
	String FAILURE_MESSAGE_THIS_EMAIL_ID_ALREADY_EXISTS_IN_THE_SYSTEM = "FAILURE_MESSAGE_THIS_EMAIL_ID_ALREADY_EXISTS_IN_THE_SYSTEM";
}
