package com.constants.components;

import com.constants.ApplicationConstants;
import com.constants.VelocityConstants;
import com.utils.localization.Message;

public interface CommonsConstants extends ApplicationConstants {
	
	String MESG_PROPERTY_FILE_NAME_WEB_SERVICE_COMMON = "spring.components.webserviceCommon";
	
	String INPUT_FILE_4 = "inputFile4";
	String INPUT_FILE_3 = "inputFile3";
	String INPUT_FILE_2 = "inputFile2";
	String INPUT_FILE_1 = "inputFile1";
	String ACCESSOPTIONS = "accessoptions";
	String USERNAME = "username";
	String MENU = "menu";
	String LAST_DEPLOYED_VERSION_AND_DATE = "lastDeployedVersionAndDate";
	String DIVERTED_EMAIL_ID = "divertedEmailId";
	String IS_EMAIL_SENDING_ACTIVE = "isEmailSendingActive";
	String SUPPORT_EMAIL = "supportEmail";
	String FILE_SYSTEM_LINKED = "fileSystemLinked";
	String DB_NAME = "dbName";
	String SERVER_NAME = "serverName";
	
	Double MAXIMUM_FILE_SIZE_FOR_EMAIL_DOCUMENTS_IN_MB = Double.valueOf(Message.getMessageFromFile(MESG_PROPERTY_FILE_NAME_WEB_SERVICE_COMMON, "MAXIMUM_ACCEPTABLE_FILE_SIZE_IN_MB").trim());
	String ACCEPTABLE_FILE_EXTENSIONS = Message.getMessageFromFile(MESG_PROPERTY_FILE_NAME_WEB_SERVICE_COMMON, "ACCEPTABLE_FILE_EXTENSIONS").trim();
	
	String EMAIL_TEMPLATES = "emailTemplates";
	String EMAIL_TEMPLATE = "emailTemplate";
	String PARAM_TEMPLATE_ID = "templateId";
	String PARAM_ERROR_CODE = "errorCode";
	
	String VELOCITY_EMAIL_TEMPLATES_SYSTEM_FOLDER_PATH = VelocityConstants.VELOCITY_EMAIL_TEMPLATES_FOLDER_PATH + "/system";
	String ERROR_REPORT_VELOCITY_TEMPLATE_PATH = VELOCITY_EMAIL_TEMPLATES_SYSTEM_FOLDER_PATH + "/error-report.vm";
	
	// Message Constants
	String VALIDATION_MESSAGE_UNKONWN_PROPERTY = "VALIDATION_MESSAGE_UNKONWN_PROPERTY";
	String VALIDATION_MESSAGE_NO_ATTRIBUTES_CHANGED = "VALIDATION_MESSAGE_NO_ATTRIBUTES_CHANGED";
	String VALIDATION_MESSAGE_ID_ABSENT = "VALIDATION_MESSAGE_ID_ABSENT";
	String VALIDATION_MESSAGE_COMMENTS_ABSENT = "VALIDATION_MESSAGE_COMMENTS_ABSENT";
	String VALIDATION_MESSAGE_GRID_ABSENT = "VALIDATION_MESSAGE_GRID_ABSENT";
	String VALIDATION_MESSAGE_BUTTON_ABSENT = "VALIDATION_MESSAGE_BUTTON_ABSENT";
	String VALIDATION_MESSAGE_BUTTON_UNKNOWN = "VALIDATION_MESSAGE_BUTTON_UNKNOWN";
	String VALIDATION_MESSAGE_PARENT_ID_ABSENT = "VALIDATION_MESSAGE_PARENT_ID_ABSENT";
	String VALIDATION_MESSAGE_PLEASE_ENTER_REMARKS = "VALIDATION_MESSAGE_PLEASE_ENTER_REMARKS";
	String VALIDATION_MESSAGE_INVALID_RECEPIENT_ADDRESS = "VALIDATION_MESSAGE_INVALID_RECEPIENT_ADDRESS";
	String VALIDATION_MESSAGE_INVALID_SALUTATION = "VALIDATION_MESSAGE_INVALID_SALUTATION";
	String VALIDATION_MESSAGE_INVALID_GRID_REFERENCE_ACCESS = "VALIDATION_MESSAGE_INVALID_GRID_REFERENCE_ACCESS";
	String VALIDATION_MESSAGE_INVALID_BUTTON_ACTION = "VALIDATION_MESSAGE_INVALID_BUTTON_ACTION";
	String VALIDATION_MESSAGE_ACTIVE_USER_ABSENT = "VALIDATION_MESSAGE_ACTIVE_USER_ABSENT";
	String INVALID_TO_EMAIL_ADDRESS = "INVALID_TO_EMAIL_ADDRESS";
	String INVALID_CC_EMAIL_ADDRESS = "INVALID_CC_EMAIL_ADDRESS";
	String INVALID_BCC_EMAIL_ADDRESS = "INVALID_BCC_EMAIL_ADDRESS";
	String INVALID_SUBJECT = "INVALID_SUBJECT";
	String INVALID_EXTENSION = "INVALID_EXTENSION";
	String INVALID_SIZE = "INVALID_SIZE";
	String EMAIL_SEND_SUCCESS = "EMAIL_SEND_SUCCESS";
	String[] ACCEPTABLE_FILE_EXTENSIONS_ARRAY = ACCEPTABLE_FILE_EXTENSIONS.split(COMMA);
}
