package com.constants.components;

import com.constants.VelocityConstants;

public interface CustomerConstants extends ResponseMapConstants {	
	String MESG_PROPERTY_FILE_NAME = "spring.components.customer";
	
	String VELOCITY_EMAIL_TEMPLATES_SUBSCRIBED_CUSTOMER_FOLDER_PATH = VelocityConstants.VELOCITY_EMAIL_TEMPLATES_FOLDER_PATH + "/subscribedcustomer";
	String PROFILE_CREATION_VELOCITY_TEMPLATE_PATH_SUBSCRIBED_CUSTOMER = VELOCITY_EMAIL_TEMPLATES_SUBSCRIBED_CUSTOMER_FOLDER_PATH + "/profile-created.vm";	
	String VELOCITY_PDF_TEMPLATES_SUBSCRIBED_CUSTOMER_FOLDER_PATH = VelocityConstants.VELOCITY_PDF_TEMPLATES_FOLDER_PATH + "/subscribedcustomer";
	String SUBSCRIBED_CUSTOMER_PROFILE_VELOCITY_TEMPLATE_PATH = VELOCITY_PDF_TEMPLATES_SUBSCRIBED_CUSTOMER_FOLDER_PATH + "/subscribed-customer-profile.vm";
	
	String REST_PARAM_CUSTOMER_SERIAL_ID = "customerSerialId";
			
	// Message Constants
	String INVALID_CUSTOMER_SERIAL_ID = "INVALID_CUSTOMER_SERIAL_ID";
	String PROVIDE_A_VALID_NAME = "PROVIDE_A_VALID_NAME";
	String PROVIDE_A_VALID_CONTACT_NUMBER_MOBILE = "PROVIDE_A_VALID_CONTACT_NUMBER_MOBILE";
	String PROVIDE_A_VALID_EMAIL_ID = "PROVIDE_A_VALID_EMAIL_ID";
	String SELECT_A_STUDENT_GRADE = "SELECT_A_STUDENT_GRADE";
	String SELECT_VALID_MULTIPLE_SUBJECTS = "SELECT_VALID_MULTIPLE_SUBJECTS";
	String SELECT_VALID_LOCATION = "SELECT_VALID_LOCATION";
	String PROVIDE_ADDRESS_DETAILS = "PROVIDE_ADDRESS_DETAILS";
}
