package com.constants.components;

public interface Form2Constants extends FormConstants {
	
	String FORM2_TABLE_NAME = "FORM2";
	
	String FORM2_COLUMN_NAME_FOR_EMP_ID = "EMP_ID";
	String FORM2_COLUMN_NAME_FOR_NAME = "NAME";
	String FORM2_COLUMN_NAME_FOR_FATHER_NAME = "FATHER_NAME";
	String FORM2_COLUMN_NAME_FOR_DATE_OF_BIRTH = "DATE_OF_BIRTH";
	String FORM2_COLUMN_NAME_FOR_GENDER = "GENDER";
	String FORM2_COLUMN_NAME_FOR_MARITAL_STATUS = "MARITAL_STATUS";
	String FORM2_COLUMN_NAME_FOR_ACCOUNT_NUMBER = "ACCOUNT_NUMBER";
	String FORM2_COLUMN_NAME_FOR_PERMANENT_ADDRESS = "PERMANENT_ADDRESS";
	String FORM2_COLUMN_NAME_FOR_TEMPORARY_ADDRESS_SAME_AS_PERMAMENT = "TEMP_ADD_SAME";
	String FORM2_COLUMN_NAME_FOR_TEMPORARY_ADDRESS = "TEMPORARY_ADDRESS";
	String FORM2_COLUMN_NAME_FOR_DATE_OF_JOINING_EPF = "DATE_OF_EPF_JOIN";
	String FORM2_COLUMN_NAME_FOR_DATE_OF_JOINING_EPS = "DATE_OF_EPS_JOIN";
	
	
	int LENGTH_LIMIT_FOR_EMP_ID = 11;
	int LENGTH_LIMIT_FOR_NAME = 50;
	int LENGTH_LIMIT_FOR_GENDER = 1;
	int LENGTH_LIMIT_FOR_ACCOUNT_NUMBER = 15;
	int LENGTH_LIMIT_FOR_PERMANENT_ADDRESS = 1000;
	int LENGTH_LIMIT_FOR_DATE_OF_BIRTH = 7;
	
	String DOWNLOADED_PDF_FORM_NAME = "_India_Provident_Form_Nomination_Form";
	
	String VELOCITY_TEMPLATE_PATH = VELOCITY_TEMPLATES_FOLDER_PATH + "/form2/form2.vm";
}
