package com.constants.components;

import com.constants.VelocityConstants;

public interface SalesConstants extends ResponseMapConstants {
	
	String BUTTON_ACTION_TO_BE_MAPPED = "toBeMapped";
	String BUTTON_ACTION_ABORTED = "aborted";
	String BUTTON_ACTION_PENDING = "pending";
	String BUTTON_ACTION_DEMO_READY = "demoReady";
	String BUTTON_ACTION_CANCEL = "cancel";
	
	String VELOCITY_EMAIL_TEMPLATES_SALES_PATH = VelocityConstants.VELOCITY_EMAIL_TEMPLATES_FOLDER_PATH + "/sales";
	
	String MESG_PROPERTY_FILE_NAME = "spring.components.sales";
	
	String SUBSCRIPTION_PACKAGE_ID_MISSING = "SUBSCRIPTION_PACKAGE_ID_MISSING";
	String INVALID_PACKAGE_BILLING_TYPE = "INVALID_PACKAGE_BILLING_TYPE";
	String INVALID_FINALIZED_RATE = "INVALID_FINALIZED_RATE";
	String INVALID_IS_CUSTOMER_GRIEVED = "INVALID_IS_CUSTOMER_GRIEVED";
	String INVALID_CUSTOMER_HAPPINESS_INDEX = "INVALID_CUSTOMER_HAPPINESS_INDEX";
	String INVALID_CUSTOMER_REMARKS = "INVALID_CUSTOMER_REMARKS";
	String INVALID_IS_TUTOR_GRIEVED = "INVALID_IS_TUTOR_GRIEVED";
	String INVALID_TUTOR_HAPPINESS_INDEX = "INVALID_TUTOR_HAPPINESS_INDEX";
	String INVALID_TUTOR_REMARKS = "INVALID_TUTOR_REMARKS";
	String INVALID_ADMIN_REMARKS = "INVALID_ADMIN_REMARKS";
}
