package com.constants.components;

public interface SelectLookupConstants extends CommonsConstants {
	
	String SELECT_LOOKUP_TABLE_YES_NO_LOOKUP = "YES_NO_LOOKUP";
	String SELECT_LOOKUP_TABLE_PREFERRED_TIME_LOOKUP = "PREFERRED_TIME_LOOKUP";
	String SELECT_LOOKUP_TABLE_LOCATIONS_LOOKUP = "LOCATIONS_LOOKUP";
	String SELECT_LOOKUP_TABLE_SUBJECTS_LOOKUP = "SUBJECTS_LOOKUP";
	String SELECT_LOOKUP_TABLE_TRANSPORT_MODE_LOOKUP = "TRANSPORT_MODE_LOOKUP";
	String SELECT_LOOKUP_TABLE_PROFESSION_LOOKUP = "PROFESSION_LOOKUP";
	String SELECT_LOOKUP_TABLE_QUALIFICATION_LOOKUP = "QUALIFICATION_LOOKUP";
	String SELECT_LOOKUP_TABLE_GENDER_LOOKUP = "GENDER_LOOKUP";
	String SELECT_LOOKUP_TABLE_STUDENT_GRADE_LOOKUP = "STUDENT_GRADE_LOOKUP";
	String SELECT_LOOKUP_TABLE_PREFERRED_TEACHING_TYPE_LOOKUP = "PREFERRED_TEACHING_TYPE_LOOKUP";
	String SELECT_LOOKUP_TABLE_REFERENCE_LOOKUP = "REFERENCE_LOOKUP";
	String SELECT_LOOKUP_TABLE_DOCUMENT_TYPE_LOOKUP = "DOCUMENT_TYPE_LOOKUP";
	String SELECT_LOOKUP_TABLE_EMAIL_TEMPLATE_LOOKUP = "EMAIL_TEMPLATE_LOOKUP";
	String SELECT_LOOKUP_TABLE_PUBLIC_APPLICATION_STATUS_LOOKUP = "PUBLIC_APPLICATION_STATUS_LOOKUP";
	String SELECT_LOOKUP_TABLE_QUERY_STATUS_LOOKUP = "QUERY_STATUS_LOOKUP";
	String SELECT_LOOKUP_TABLE_COMPLAINT_STATUS_LOOKUP = "COMPLAINT_STATUS_LOOKUP";
	String SELECT_LOOKUP_TABLE_USER_LOOKUP = "USER_LOOKUP";
	
	String SELECT_LOOKUP_TABLE_NAME = "SELECT_LOOKUP_TABLE_NAME";
}
