package com.constants.components;

public interface SubscriptionPackageConstants extends SalesConstants {
	
	String BUTTON_ACTIVATE_SUBSCRIPTION = "activateSubscription";
	String BUTTON_END_SUBSCRIPTION = "endSubscription";
	String BUTTON_CREATE_ASSIGNMENT_SUBSCRIPTION = "createAssignment";
	
	String SUBSCRIPTION_ALREADY_ACTIVE = "SUBSCRIPTION_ALREADY_ACTIVE";
	String SUBSCRIPTION_ALREADY_TERMINATED = "SUBSCRIPTION_ALREADY_TERMINATED";
	String SUBSCRIPTION_NOT_ACTIVE = "SUBSCRIPTION_NOT_ACTIVE";
	String SUBSCRIPTION_HAS_RUNNING_ASSIGNMENT = "SUBSCRIPTION_HAS_RUNNING_ASSIGNMENT";
	
	String VELOCITY_EMAIL_TEMPLATES_SUBSCRIPTION_PATH = VELOCITY_EMAIL_TEMPLATES_SALES_FOLDER_PATH + "/subscriptionpackage";
	String VELOCITY_TEMPLATES_SUBSCRIPTION_ACTIVATED_CLIENT_EMAIL_PATH = VELOCITY_EMAIL_TEMPLATES_SUBSCRIPTION_PATH + "/subscription-package-activated-client-email.vm";
	String VELOCITY_TEMPLATES_SUBSCRIPTION_ACTIVATED_TUTOR_EMAIL_PATH = VELOCITY_EMAIL_TEMPLATES_SUBSCRIPTION_PATH + "/subscription-package-activated-tutor-email.vm";
	String VELOCITY_TEMPLATES_ASSIGNMENT_STARTED_CLIENT_EMAIL_PATH = VELOCITY_EMAIL_TEMPLATES_SUBSCRIPTION_PATH + "/package-asignment-started-client-email.vm";
	String VELOCITY_TEMPLATES_ASSIGNMENT_STARTED_TUTOR_EMAIL_PATH = VELOCITY_EMAIL_TEMPLATES_SUBSCRIPTION_PATH + "/package-assignment-started-tutor-email.vm";
	
	// Contract
	String VELOCITY_PDF_TEMPLATES_SUBSCRIPTION_PACKAGE_PATH = VELOCITY_PDF_TEMPLATES_SALES_FOLDER_PATH + "/subscriptionpackage";
	String SUBSCRIPTION_PACKAGE_CONTRACT_PDF_PATH = VELOCITY_PDF_TEMPLATES_SUBSCRIPTION_PACKAGE_PATH + "/subscription-package-contract.vm";
	
	String CUSTOMER_SUBSCRIPTION_PACKAGE_CONTRACT = "01";
	
	String BUTTON_START_ASSIGNMENT = "startAssignment";
	String BUTTON_END_ASSIGNMENT = "endAssignment";
	
	String PACKAGE_ASSIGNMENT_ALREADY_RUNNING = "PACKAGE_ASSIGNMENT_ALREADY_RUNNING";
	String PACKAGE_ASSIGNMENT_ALREADY_COMPLETED = "PACKAGE_ASSIGNMENT_ALREADY_COMPLETED";
}
