package com.constants.components;

public interface SubscriptionPackageConstants extends ResponseMapConstants {
	
	String BUTTON_ACTIVATE_SUBSCRIPTION = "activateSubscription";
	String BUTTON_END_SUBSCRIPTION = "endSubscription";
	String BUTTON_CREATE_ASSIGNMENT_SUBSCRIPTION = "createAssignment";
	
	String SUBSCRIPTION_ALREADY_ACTIVE = "SUBSCRIPTION_ALREADY_ACTIVE";
	String SUBSCRIPTION_ALREADY_TERMINATED = "SUBSCRIPTION_ALREADY_TERMINATED";
	String SUBSCRIPTION_NOT_ACTIVE = "SUBSCRIPTION_NOT_ACTIVE";
	String SUBSCRIPTION_HAS_RUNNING_ASSIGNMENT = "SUBSCRIPTION_HAS_RUNNING_ASSIGNMENT";
}
