package com.constants.components;

import com.constants.VelocityConstants;
import com.utils.localization.Message;

public interface TutorConstants extends ResponseMapConstants {
	
	String MESG_PROPERTY_FILE_NAME = "spring.components.tutor";
	
	String REQUEST_PARAM_TUTOR_SERIAL_ID = "tutorSerialId";
	String REQUEST_PARAM_DOCUMENT_SERIAL_ID = "documentSerialId";
	String REQUEST_PARAM_DOCUMENT_TYPE = "documentType";
	String REQUEST_PARAM_INPUT_FILE_PHOTO = "inputFilePhoto";
	String REQUEST_PARAM_INPUT_FILE_AADHAAR_CARD = "inputFileAadhaarCard";
	String REQUEST_PARAM_INPUT_FILE_PAN_CARD = "inputFilePANCard";
	
	String RESPONSE_MAP_REMOVED_DOCUMENT_TYPE = "removedDocumentType";
	
	Double MAXIMUM_FILE_SIZE_FOR_DOCUMENTS_IN_MB = 2D;
	
	String DOCUMENT_TYPE_PAN_CARD = "01";
	String DOCUMENT_TYPE_PROFILE_PHOTO = "02";
	String DOCUMENT_TYPE_AADHAAR_CARD = "03";
	
	String VELOCITY_EMAIL_TEMPLATES_REGISTERED_TUTOR_FOLDER_PATH = VelocityConstants.VELOCITY_EMAIL_TEMPLATES_FOLDER_PATH + "/registeredtutor";
	String REGISTERED_TUTOR_DOCUMENT_REJECTED_VELOCITY_TEMPLATE_PATH = VELOCITY_EMAIL_TEMPLATES_REGISTERED_TUTOR_FOLDER_PATH + "/document-rejected.vm";
	String REGISTERED_TUTOR_DOCUMENT_REMINDER_VELOCITY_TEMPLATE_PATH = VELOCITY_EMAIL_TEMPLATES_REGISTERED_TUTOR_FOLDER_PATH + "/document-reminder.vm";
	String PROFILE_CREATION_VELOCITY_TEMPLATE_PATH = VELOCITY_EMAIL_TEMPLATES_REGISTERED_TUTOR_FOLDER_PATH + "/profile-created.vm";
	
	String VELOCITY_PDF_TEMPLATES_REGISTERED_TUTOR_FOLDER_PATH = VelocityConstants.VELOCITY_PDF_TEMPLATES_FOLDER_PATH + "/registeredtutor";
	String REGISTERED_TUTOR_PROFILE_VELOCITY_TEMPLATE_PATH = VELOCITY_PDF_TEMPLATES_REGISTERED_TUTOR_FOLDER_PATH + "/registered-tutor-profile.vm";

	String VALID_FILE_TYPE_FOR_DOCUMENTS = Message.getMessageFromFile(MESG_PROPERTY_FILE_NAME, "VALID_FILE_TYPE_FOR_DOCUMENTS").trim();
	Double MAXIMUM_VALID_FILE_SIZE_FOR_DOCUMENTS_IN_MB = Double.valueOf(Message.getMessageFromFile(MESG_PROPERTY_FILE_NAME, "MAXIMUM_VALID_FILE_SIZE_FOR_DOCUMENTS_IN_MB").trim());

	// Message Constants
	String INVALID_TUTOR_SERIAL_ID = "INVALID_TUTOR_SERIAL_ID";
	String INVALID_DOCUMENT_SERIAL_ID = "INVALID_DOCUMENT_SERIAL_ID";
	String INVALID_BANK_DETAIL_SERIAL_ID = "INVALID_BANK_DETAIL_SERIAL_ID";
	String DOCUMENT_TYPE_MISSING = "REGISTERED_TUTOR_DOCUMENT_TYPE_MISSING";
}
