INSERT INTO GENDER_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('M', 'Male', NULL, NULL);
INSERT INTO GENDER_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('F', 'Female', NULL, NULL);
INSERT INTO GENDER_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('O', 'Rather not say', NULL, NULL);

INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('BTech', 'Bachelor of Technology', 'Graduation', NULL);
INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('BCom', 'Bachelor of Commerce', 'Graduation', NULL);
INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('MTech', 'Master of Technology', 'Post Graduation', NULL);

INSERT INTO PROFESSION_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('SE', 'Software Expert', 'IT Industry', NULL);
INSERT INTO PROFESSION_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('Prog', 'Programmer', 'IT Industry', NULL);
INSERT INTO PROFESSION_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('OMan', 'Operations Manager', 'Manufacturing', NULL);

INSERT INTO TRANSPORT_MODE_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('P', 'Public Transport', NULL, NULL);
INSERT INTO TRANSPORT_MODE_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('2-W', 'Four Wheeler', NULL, NULL);
INSERT INTO TRANSPORT_MODE_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('4-W', 'Two Wheeler', NULL, NULL);

INSERT INTO LOCATIONS_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('TP', 'Tedhi Pulia', 'North Lucknow', NULL);
INSERT INTO LOCATIONS_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('HZ', 'Hazratganj', 'East Lucknow', NULL);
INSERT INTO LOCATIONS_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('KP', 'Kapoorthala', 'Central Lucknow', NULL);

INSERT INTO PREFERRED_TIME_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('8A12P', '8 AM - 12 PM', 'Morning', NULL);
INSERT INTO PREFERRED_TIME_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('12P4P', '12 PM - 4 PM', 'Noon', NULL);
INSERT INTO PREFERRED_TIME_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('4P8P', '4 PM - 8 PM', 'Evening', NULL);

INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('C5', 'Class 5', 'Primary', NULL);
INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('C6', 'Class 6', 'Middle', NULL);
INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('C9', 'Class 9', 'High', NULL);

INSERT INTO SUBJECTS_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('Phy', 'Physics', 'Science', NULL);
INSERT INTO SUBJECTS_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('Chem', 'Chemistry', 'Science', NULL);
INSERT INTO SUBJECTS_LOOKUP(VALUE, LABEL, CATEGORY, DESCRIPTION) VALUES('Hindi', 'Hindi', 'Languages', NULL);