INSERT INTO GENDER_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('M', 'Male', NULL, 1, 1, NULL);
INSERT INTO GENDER_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('F', 'Female', NULL, 1, 2, NULL);
INSERT INTO GENDER_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('O', 'Rather not say', NULL, 1, 3, NULL);

INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('BTech', 'Bachelor of Technology', 'Graduation', 1, 2, NULL);
INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('BCom', 'Bachelor of Commerce', 'Graduation', 1, 1, NULL);
INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('MTech', 'Master of Technology', 'Post Graduation', 2, 2, NULL);
INSERT INTO QUALIFICATION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('MCom', 'Master of Commerce', 'Post Graduation', 2, 1, NULL);

INSERT INTO PROFESSION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('SE', 'Software Expert', 'IT Industry', 2, 2, NULL);
INSERT INTO PROFESSION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('Prog', 'Programmer', 'IT Industry', 2, 1, NULL);
INSERT INTO PROFESSION_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('OMan', 'Operations Manager', 'Manufacturing', 1, 1, NULL);

INSERT INTO TRANSPORT_MODE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('P', 'Public Transport', NULL, 1, 1, NULL);
INSERT INTO TRANSPORT_MODE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('2-W', 'Four Wheeler', NULL, 1, 2, NULL);
INSERT INTO TRANSPORT_MODE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('4-W', 'Two Wheeler', NULL, 1, 3, NULL);

INSERT INTO LOCATIONS_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('TP', 'Tedhi Pulia', 'North Lucknow', 2, 1, NULL);
INSERT INTO LOCATIONS_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('HZ', 'Hazratganj', 'East Lucknow', 1, 1, NULL);
INSERT INTO LOCATIONS_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('KP', 'Kapoorthala', 'Central Lucknow', 3, 1, NULL);

INSERT INTO PREFERRED_TIME_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('8A12P', '8 AM - 12 PM', 'Morning', 1, 1, NULL);
INSERT INTO PREFERRED_TIME_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('12P4P', '12 PM - 4 PM', 'Noon', 2, 1, NULL);
INSERT INTO PREFERRED_TIME_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('4P8P', '4 PM - 8 PM', 'Evening', 3, 1, NULL);

INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('C5', 'Class 5', 'Primary', 1, 1, NULL);
INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('C6', 'Class 6', 'Middle', 2, 1, NULL);
INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('C9', 'Class 9', 'High', 3, 1, NULL);
INSERT INTO STUDENT_GRADE_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('C10', 'Class 10', 'High', 3, 2, NULL);

INSERT INTO SUBJECTS_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('Phy', 'Physics', 'Science', 1, 1, NULL);
INSERT INTO SUBJECTS_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('Chem', 'Chemistry', 'Science', 1, 2, NULL);
INSERT INTO SUBJECTS_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION) VALUES('Hindi', 'Hindi', 'Languages', 2, 1, NULL);

COMMIT;