---------------------------------------------------------------------------------
--                                     SELECT DATABASE
---------------------------------------------------------------------------------
USE SEEK_MENTORE;

---------------------------------------------------------------------------------
-- Public Pages Tables
---------------------------------------------------------------------------------
SELECT * FROM BECOME_TUTOR;
SELECT * FROM FIND_TUTOR;
SELECT * FROM SUBSCRIBE_WITH_US;
SELECT * FROM SUBMIT_QUERY;

SELECT * FROM SUBSCRIBED_CUSTOMER;
SELECT * FROM REGISTERED_TUTOR;
SELECT * FROM TUTOR_DOCUMENTS;

SELECT * FROM ENQUIRIES;
SELECT * FROM TUTOR_MAPPER;

SELECT * FROM GENDER_LOOKUP;
SELECT * FROM QUALIFICATION_LOOKUP;
SELECT * FROM PROFESSION_LOOKUP;
SELECT * FROM TRANSPORT_MODE_LOOKUP;
SELECT * FROM LOCATIONS_LOOKUP;
SELECT * FROM PREFERRED_TIME_LOOKUP;
SELECT * FROM STUDENT_GRADE_LOOKUP;
SELECT * FROM SUBJECTS_LOOKUP;
SELECT * FROM REFERENCE_LOOKUP;
SELECT * FROM PREFERRED_TEACHING_TYPE_LOOKUP;

SELECT * FROM APP_ERROR_REPORT;

SELECT * FROM MAIL_QUEUE;
SELECT * FROM MAIL_ATTACHMENTS;

SELECT * FROM LOGON_TRACKER;
SELECT * FROM PASSWORD_CHANGE_TRACKER;

SELECT * FROM EMPLOYEE;


