---------------------------------------------------------------------------------
--                                     SELECT DATABASE
---------------------------------------------------------------------------------
USE SEEK_MENTORE;

---------------------------------------------------------------------------------
-- Public Pages Tables
---------------------------------------------------------------------------------
SELECT * FROM BECOME_TUTOR;
SELECT * FROM FIND_TUTOR;
SELECT * FROM SUBSCRIBE_WITH_US;
SELECT * FROM SUBMIT_QUERY;

SELECT * FROM SUBSCRIBED_CUSTOMER;
SELECT * FROM REGISTERED_TUTOR;
SELECT * FROM TUTOR_DOCUMENT;

SELECT * FROM ENQUIRIES;
SELECT * FROM TUTOR_MAPPER;
SELECT * FROM DEMO_TRACKER;

SELECT * FROM COMPLAINT;
SELECT * FROM BANK_DETAIL;
SELECT * FROM SUBSCRIPTION_PACKAGE;
SELECT * FROM ALERT_REMINDER;
SELECT * FROM TASK;
SELECT * FROM WORKFLOW;

SELECT * FROM REGISTERED_TUTOR_OTHER_EMAILS;
SELECT * FROM REGISTERED_TUTOR_OTHER_CONTACT_NUMBERS;
SELECT * FROM SUBSCRIBED_CUSTOMER_OTHER_EMAILS;
SELECT * FROM SUBSCRIBED_CUSTOMER_OTHER_CONTACT_NUMBERS;

SELECT * FROM GENDER_LOOKUP;
SELECT * FROM QUALIFICATION_LOOKUP;
SELECT * FROM PROFESSION_LOOKUP;
SELECT * FROM TRANSPORT_MODE_LOOKUP;
SELECT * FROM LOCATIONS_LOOKUP;
SELECT * FROM PREFERRED_TIME_LOOKUP;
SELECT * FROM STUDENT_GRADE_LOOKUP;
SELECT * FROM SUBJECTS_LOOKUP;
SELECT * FROM REFERENCE_LOOKUP;
SELECT * FROM PREFERRED_TEACHING_TYPE_LOOKUP;
SELECT * FROM DOCUMENT_TYPE_LOOKUP;
SELECT * FROM EMAIL_TEMPLATE_LOOKUP;
SELECT * FROM PUBLIC_APPLICATION_STATUS_LOOKUP;
SELECT * FROM QUERY_STATUS_LOOKUP;
SELECT * FROM COMPLAINT_STATUS_LOOKUP;
SELECT * FROM USER_LOOKUP;
SELECT * FROM ENQUIRY_MATCH_STATUS_LOOKUP;
SELECT * FROM TUTOR_MAPPING_STATUS_LOOKUP;
SELECT * FROM DEMO_STATUS_LOOKUP;

SELECT * FROM APP_ERROR_REPORT;
SELECT * FROM AWS_S3_DELETE_REPORT;

SELECT * FROM MAIL_QUEUE;
SELECT * FROM MAIL_ATTACHMENTS;
SELECT * FROM EMAIL_TEMPLATE;

SELECT * FROM LOGON_TRACKER;
SELECT * FROM PASSWORD_CHANGE_TRACKER;

SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_OTHER_EMAILS;
SELECT * FROM EMPLOYEE_OTHER_CONTACT_NUMBERS;


