package com.constants;

public interface ErrorConstants extends ApplicationConstants {
	
	String MESG_PROPERTY_FILE_NAME = "spring.errorMessages";
	
	String MESG_PROPERTY_ERROR_UNKNOWN = "ERROR_UNKNOWN";
	String MESG_PROPERTY_ERROR_SERVER_ERROR = "ERROR_SERVER_ERROR";
	String MESG_PROPERTY_ERROR_SITE_UNDER_MAINTENANCE = "ERROR_SITE_UNDER_MAINTENANCE";
	String MESG_PROPERTY_ERROR_LOGIN_BLOCKED = "ERROR_LOGIN_BLOCKED";
	String MESG_PROPERTY_ERROR_PAGE_UNDER_MAINTENANCE = "ERROR_PAGE_UNDER_MAINTENANCE";
	String MESG_PROPERTY_ERROR_ACCESS_DENIED = "ERROR_ACCESS_DENIED";
	String ERROR_TEXT = "errorText";
	String ERROR_IMAGE_SRC = "errorImageSrc";
	String ERROR_CODE_105 = "105";
	String ERROR_CODE_104 = "104";
	String ERROR_CODE_103 = "103";
	String ERROR_CODE_102 = "102";
	String ERROR_CODE_101 = "101";
}
