package com.constants;

import com.constants.components.ResponseMapConstants;

public interface GridComponentConstants extends ResponseMapConstants {
	
	String COLUMN_SORTER_ATTRIBUTE_ORDER = "order";
	String COLUMN_SORTER_ATTRIBUTE_COLUMN_NAME = "columnName";
	String COLUMN_FILTER_VALUE_LIST_VALUE = "listValue";
	String COLUMN_FILTER_VALUE_GREATER_THAN = "greaterThan";
	String COLUMN_FILTER_VALUE_EQUAL_TO = "equalTo";
	String COLUMN_FILTER_VALUE_LESS_THAN = "lessThan";
	String COLUMN_FILTER_VALUE_LOCAL_TIMEZONE_OFFSET_IN_MILLISECONDS = "localTimezoneOffsetInMilliseconds";
	String COLUMN_FILTER_VALUE_AFTER_DATE_MILLIS = "afterDateMillis";
	String COLUMN_FILTER_VALUE_ON_DATE_MILLIS = "onDateMillis";
	String COLUMN_FILTER_VALUE_BEFORE_DATE_MILLIS = "beforeDateMillis";
	String COLUMN_FILTER_VALUE_TEXT_CASE_SENSITIVE_SEARCH = "textCaseSensitiveSearch";
	String COLUMN_FILTER_VALUE_STRING_VALUE = "stringValue";
	String COLUMN_FILTER_MAPPING_LIST = "list";
	String COLUMN_FILTER_MAPPING_NUMBER = "number";
	String COLUMN_FILTER_MAPPING_DATE = "date";
	String COLUMN_FILTER_MAPPING_STRING = "string";
	String COLUMN_FILTER_ATTRIBUTE_COLUMN_ID = "columnId";
	String COLUMN_FILTER_ATTRIBUTE_MULTILIST = "multiList";
	String COLUMN_FILTER_ATTRIBUTE_CLUBBED_FILTER_MAPPING = "clubbedFilterMapping";
	String COLUMN_FILTER_ATTRIBUTE_CLUBBED_FILTER_PROPERTIES = "clubbedFilterProperties";
	String COLUMN_FILTER_ATTRIBUTE_MAPPING = "mapping";
	String COLUMN_FILTER_ATTRIBUTE_TYPE = "type";
	String COLUMN_FILTER_ATTRIBUTE_ID = "id";
	String COLUMN_SORTER_ATTRIBUTE_COLUMN_ID = COLUMN_FILTER_ATTRIBUTE_COLUMN_ID;
	String COLUMN_SORTER_ATTRIBUTE_MAPPING = COLUMN_FILTER_ATTRIBUTE_MAPPING;
	String COLUMN_SORTER_ATTRIBUTE_TYPE = COLUMN_FILTER_ATTRIBUTE_TYPE;
	String COLUMN_SORTER_ATTRIBUTE_ID = COLUMN_FILTER_ATTRIBUTE_ID;
	String COLUMN_SORTER_ATTRIBUTE_CLUBBED_FILTER_MAPPING = "clubbedSorterMapping";
	String COLUMN_SORTER_ATTRIBUTE_CLUBBED_FILTER_PROPERTIES = "clubbedSorterProperties";
	String STRIPPED_DATED_MILLISECONDS_CALCULATOR_QUERY = "(UNIX_TIMESTAMP(date(FROM_UNIXTIME(#MAPPING_COLUMN#/1000)))*1000)";
	String MAPPING_COLUMN_REPLACE_TEXT = "#MAPPING_COLUMN#";
	
	String DUMMY_COLUMN_FILTER = "DUMMY_COLUMN_FILTER";
	String DUMMY_COLUMN = "DUMMY_COLUMN";

	
	String GRID_COMPONENT_TOTAL_RECORDS = "totalRecords";
	String GRID_COMPONENT_RECORD_DATA = "data";
	
	String LIKE_ALL_APPENDER_CLOSURE = "%' ";
	String LIKE_ALL_APPENDER = " like '%";
	String UPPER_APPENDER = "upper(";
	String COMMA_APPENDER = ", ";
	String DESCENDING_ORDER = "DESC";
	String ASCENDING_ORDER = "ASC";
	String RIGHT_BRACKET_APPENDER = " ) ";
	String OR_APPENDER = " OR ";
	String LEFT_BRACKET_APPENDER = " ( ";
	String AND_APPENDER = " AND ";
	String WHERE_APPENDER = " WHERE ";
	String ORDER_BY_APPENDER = " ORDER BY ";
	String GREATER_THAN_APPENDER = " > ";
	String EQUAL_TO_APPENDER = " = ";
	String LESS_THAN_APPENDER = " < ";
	String ORDER_BY_CLAUSE = "ORDER BY";
	String AND_CLAUSE = "AND";
	String WHERE_CLAUSE = "WHERE";
	String IN_APPENDER = " IN (";
	
	String STANDARD_EXTRA_PARAM_SECURE_SELECTION_COLUMN_BUTTONS = "secureSelectionColumnButtons";
	String STANDARD_EXTRA_PARAM_HAS_SELECTION_BUTTONS = "hasSelectionButtons";
	String STANDARD_EXTRA_PARAM_SECURE_ACTION_COLUMN_BUTTONS = "secureActionColumnButtons";
	String STANDARD_EXTRA_PARAM_HAS_ACTION_BUTTONS = "hasActionButtons";
	
	String GRID_RECORD_DATA_TOTAL_RECORDS = "gridRecordDataTotalRecords";
}
