package com.constants;

public interface MessageConstants extends ApplicationConstants {
	
	String MESG_PROPERTY_FILE_NAME = "spring.application";
	
	String APPLICATION_NAME = "APPLICATION_NAME";
	String APPLICATION_HEALTH_GOOD = "APPLICATION_HEALTH_GOOD";
	String APPLICATION_HEALTH_BAD = "APPLICATION_HEALTH_BAD";
	String ERROR_MESSAGE_UNAVAILABLE = "ERROR_MESSAGE_UNAVAILABLE";
	String LAST_STABLE_PROD_VERSION_AND_DATE = "LAST_STABLE_PROD_VERSION_AND_DATE";
	String SERVER_URL_LOCAL = "SERVER_URL_LOCAL";
	String SERVER_URL_DEV = "SERVER_URL_DEV";
	String SERVER_URL_PROD = "SERVER_URL_PROD";
	String IMAGE_SERVER_URL = "IMAGE_SERVER_URL";
	String BACKOFFICE_URL_LOCAL = "BACKOFFICE_URL_LOCAL";
	String BACKOFFICE_URL_DEV = "BACKOFFICE_URL_DEV";
	String BACKOFFICE_URL_PROD = "BACKOFFICE_URL_PROD";
}
