USE SEEK_MENTORE;

CREATE TABLE LOGON_TRACKER(
LOGON_ID INT NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(100) NOT NULL,
USER_TYPE VARCHAR(100) NOT NULL,
LOGIN_TIME TIMESTAMP NOT NULL,
LOGIN_FROM VARCHAR(1000),
MACHINE_IP VARCHAR(1000),
PRIMARY KEY (LOGON_ID));

CREATE TABLE PASSWORD_CHANGE_TRACKER(
PASSWORD_CHANGE_ID INT NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(100) NOT NULL,
USER_TYPE VARCHAR(100) NOT NULL,
CHANGE_TIME TIMESTAMP NOT NULL,
ENCYPTED_PASSWORD_OLD VARCHAR(1000) NOT NULL,
ENCYPTED_PASSWORD_NEW VARCHAR(1000) NOT NULL,
PRIMARY KEY (PASSWORD_CHANGE_ID));
