USE SEEK_MENTORE;

ALTER table FIND_TUTOR ADD COLUMN IS_DATA_MIGRATED VARCHAR(2);
ALTER table FIND_TUTOR ADD COLUMN WHEN_MIGRATED TIMESTAMP;
-- Executed till here In Prod Do not write any more create new file