USE SEEK_MENTORE;

ALTER TABLE DEMO_TRACKER
ADD COLUMN DEMO_DATE_AND_TIME_MILLIS INT NOT NULL;

ALTER TABLE TUTOR_MAPPER
ADD COLUMN DEMO_DATE_AND_TIME_MILLIS INT NOT NULL;

ALTER TABLE TUTOR_MAPPER
DROP COLUMN DEMO_DATE_AND_TIME;

ALTER TABLE TUTOR_MAPPER
DROP COLUMN DEMO_DATE_AND_TIME_MILLIS;

-- Old queries

ALTER TABLE DEMO_TRACKER
DROP COLUMN DEMO_DATE_AND_TIME_MILLIS;

ALTER TABLE TUTOR_MAPPER
ADD COLUMN DEMO_DATE_AND_TIME TIMESTAMP;

ALTER TABLE REGISTERED_TUTOR
ADD COLUMN RECORD_LAST_UPDATED_MILLIS BIGINT;

ALTER TABLE SUBSCRIBED_CUSTOMER
ADD COLUMN RECORD_LAST_UPDATED_MILLIS BIGINT;

ALTER TABLE TUTOR_DOCUMENTS
ADD COLUMN ACTION_DATE_MILLIS BIGINT;

UPDATE REGISTERED_TUTOR SET
RECORD_LAST_UPDATED_MILLIS = UNIX_TIMESTAMP(RECORD_LAST_UPDATED) * 1000;

UPDATE SUBSCRIBED_CUSTOMER SET
RECORD_LAST_UPDATED_MILLIS = UNIX_TIMESTAMP(RECORD_LAST_UPDATED) * 1000;

UPDATE TUTOR_DOCUMENTS SET
ACTION_DATE_MILLIS = UNIX_TIMESTAMP(ACTION_DATE) * 1000;

ALTER TABLE REGISTERED_TUTOR
DROP COLUMN RECORD_LAST_UPDATED;

ALTER TABLE SUBSCRIBED_CUSTOMER
DROP COLUMN RECORD_LAST_UPDATED;

ALTER TABLE TUTOR_DOCUMENTS
DROP COLUMN ACTION_DATE;

ALTER TABLE BECOME_TUTOR
ADD COLUMN APPLICATION_DATE_MILLIS BIGINT,
ADD COLUMN CONTACTED_DATE_MILLIS BIGINT,
ADD COLUMN VERIFICATION_DATE_MILLIS BIGINT,
ADD COLUMN SUGGESTION_DATE_MILLIS BIGINT,
ADD COLUMN RECONTACTED_DATE_MILLIS BIGINT,
ADD COLUMN SELECTION_DATE_MILLIS BIGINT,
ADD COLUMN REJECTION_DATE_MILLIS BIGINT,
ADD COLUMN PREVIOUS_APPLICATION_DATE_MILLIS BIGINT,
ADD COLUMN RECORD_LAST_UPDATED_MILLIS BIGINT,
ADD COLUMN WHEN_MIGRATED_MILLIS BIGINT;

UPDATE BECOME_TUTOR SET
APPLICATION_DATE_MILLIS = UNIX_TIMESTAMP(APPLICATION_DATE) * 1000,
CONTACTED_DATE_MILLIS = UNIX_TIMESTAMP(CONTACTED_DATE) * 1000,
VERIFICATION_DATE_MILLIS = UNIX_TIMESTAMP(VERIFICATION_DATE) * 1000,
SUGGESTION_DATE_MILLIS = UNIX_TIMESTAMP(SUGGESTION_DATE) * 1000,
RECONTACTED_DATE_MILLIS = UNIX_TIMESTAMP(RECONTACTED_DATE) * 1000,
SELECTION_DATE_MILLIS = UNIX_TIMESTAMP(SELECTION_DATE) * 1000,
REJECTION_DATE_MILLIS = UNIX_TIMESTAMP(REJECTION_DATE) * 1000,
PREVIOUS_APPLICATION_DATE_MILLIS = UNIX_TIMESTAMP(PREVIOUS_APPLICATION_DATE) * 1000,
RECORD_LAST_UPDATED_MILLIS = UNIX_TIMESTAMP(RECORD_LAST_UPDATED) * 1000,
WHEN_MIGRATED_MILLIS = UNIX_TIMESTAMP(WHEN_MIGRATED) * 1000;

ALTER TABLE BECOME_TUTOR
DROP COLUMN APPLICATION_DATE,
DROP COLUMN CONTACTED_DATE,
DROP COLUMN VERIFICATION_DATE,
DROP COLUMN SUGGESTION_DATE,
DROP COLUMN SELECTION_DATE,
DROP COLUMN REJECTION_DATE,
DROP COLUMN PREVIOUS_APPLICATION_DATE,
DROP COLUMN RECORD_LAST_UPDATED,
DROP COLUMN WHEN_MIGRATED;

ALTER TABLE BECOME_TUTOR
ADD COLUMN UPDATED_BY VARCHAR(100);

UPDATE BECOME_TUTOR SET
UPDATED_BY = 'SYSTEM';

ALTER TABLE FIND_TUTOR
ADD COLUMN ENQUIRY_DATE_MILLIS BIGINT,
ADD COLUMN CONTACTED_DATE_MILLIS BIGINT,
ADD COLUMN VERIFICATION_DATE_MILLIS BIGINT,
ADD COLUMN SUGGESTION_DATE_MILLIS BIGINT,
ADD COLUMN RECONTACTED_DATE_MILLIS BIGINT,
ADD COLUMN SELECTION_DATE_MILLIS BIGINT,
ADD COLUMN REJECTION_DATE_MILLIS BIGINT,
ADD COLUMN RECORD_LAST_UPDATED_MILLIS BIGINT,
ADD COLUMN WHEN_MIGRATED_MILLIS BIGINT;

UPDATE FIND_TUTOR SET
ENQUIRY_DATE_MILLIS = UNIX_TIMESTAMP(ENQUIRY_DATE) * 1000,
CONTACTED_DATE_MILLIS = UNIX_TIMESTAMP(CONTACTED_DATE) * 1000,
VERIFICATION_DATE_MILLIS = UNIX_TIMESTAMP(VERIFICATION_DATE) * 1000,
SUGGESTION_DATE_MILLIS = UNIX_TIMESTAMP(SUGGESTION_DATE) * 1000,
RECONTACTED_DATE_MILLIS = UNIX_TIMESTAMP(RECONTACTED_DATE) * 1000,
SELECTION_DATE_MILLIS = UNIX_TIMESTAMP(SELECTION_DATE) * 1000,
REJECTION_DATE_MILLIS = UNIX_TIMESTAMP(REJECTION_DATE) * 1000,
RECORD_LAST_UPDATED_MILLIS = UNIX_TIMESTAMP(RECORD_LAST_UPDATED) * 1000,
WHEN_MIGRATED_MILLIS = UNIX_TIMESTAMP(WHEN_MIGRATED) * 1000;

ALTER TABLE FIND_TUTOR
DROP COLUMN ENQUIRY_DATE,
DROP COLUMN CONTACTED_DATE,
DROP COLUMN VERIFICATION_DATE,
DROP COLUMN SUGGESTION_DATE,
DROP COLUMN SELECTION_DATE,
DROP COLUMN REJECTION_DATE,
DROP COLUMN RECORD_LAST_UPDATED,
DROP COLUMN WHEN_MIGRATED;

ALTER TABLE FIND_TUTOR
ADD COLUMN UPDATED_BY VARCHAR(100);

UPDATE FIND_TUTOR SET
UPDATED_BY = 'SYSTEM';

ALTER TABLE BECOME_TUTOR
DROP COLUMN RECONTACTED_DATE;

ALTER TABLE FIND_TUTOR
DROP COLUMN RECONTACTED_DATE;

ALTER TABLE SUBSCRIBE_WITH_US
ADD COLUMN APPLICATION_DATE_MILLIS BIGINT,
ADD COLUMN CONTACTED_DATE_MILLIS BIGINT,
ADD COLUMN VERIFICATION_DATE_MILLIS BIGINT,
ADD COLUMN SUGGESTION_DATE_MILLIS BIGINT,
ADD COLUMN RECONTACTED_DATE_MILLIS BIGINT,
ADD COLUMN SELECTION_DATE_MILLIS BIGINT,
ADD COLUMN REJECTION_DATE_MILLIS BIGINT,
ADD COLUMN RECORD_LAST_UPDATED_MILLIS BIGINT,
ADD COLUMN WHEN_MIGRATED_MILLIS BIGINT;

UPDATE SUBSCRIBE_WITH_US SET
APPLICATION_DATE_MILLIS = UNIX_TIMESTAMP(APPLICATION_DATE) * 1000,
CONTACTED_DATE_MILLIS = UNIX_TIMESTAMP(CONTACTED_DATE) * 1000,
VERIFICATION_DATE_MILLIS = UNIX_TIMESTAMP(VERIFICATION_DATE) * 1000,
SUGGESTION_DATE_MILLIS = UNIX_TIMESTAMP(SUGGESTION_DATE) * 1000,
RECONTACTED_DATE_MILLIS = UNIX_TIMESTAMP(RECONTACTED_DATE) * 1000,
SELECTION_DATE_MILLIS = UNIX_TIMESTAMP(SELECTION_DATE) * 1000,
REJECTION_DATE_MILLIS = UNIX_TIMESTAMP(REJECTION_DATE) * 1000,
RECORD_LAST_UPDATED_MILLIS = UNIX_TIMESTAMP(RECORD_LAST_UPDATED) * 1000;

ALTER TABLE SUBSCRIBE_WITH_US
DROP COLUMN APPLICATION_DATE,
DROP COLUMN CONTACTED_DATE,
DROP COLUMN VERIFICATION_DATE,
DROP COLUMN SUGGESTION_DATE,
DROP COLUMN RECONTACTED_DATE,
DROP COLUMN SELECTION_DATE,
DROP COLUMN REJECTION_DATE,
DROP COLUMN RECORD_LAST_UPDATED;

ALTER TABLE SUBSCRIBE_WITH_US
ADD COLUMN UPDATED_BY VARCHAR(100);

-- done
UPDATE SUBSCRIBE_WITH_US SET
UPDATED_BY = 'SYSTEM';

ALTER TABLE SUBSCRIBE_WITH_US
ADD COLUMN IS_DATA_MIGRATED VARCHAR(2);

