USE SEEK_MENTORE;

UPDATE REFERENCE_LOOKUP SET VALUE = '01' WHERE VALUE = 1 OR VALUE = 01; 
UPDATE REFERENCE_LOOKUP SET VALUE = '02' WHERE VALUE = 2 OR VALUE = 02; 
UPDATE REFERENCE_LOOKUP SET VALUE = '03' WHERE VALUE = 3 OR VALUE = 03; 
UPDATE REFERENCE_LOOKUP SET VALUE = '04' WHERE VALUE = 4 OR VALUE = 04; 
UPDATE REFERENCE_LOOKUP SET VALUE = '05' WHERE VALUE = 5 OR VALUE = 05; 

UPDATE BECOME_TUTOR SET REFERENCE = '01' WHERE REFERENCE = 1 OR REFERENCE = 01; 
UPDATE BECOME_TUTOR SET REFERENCE = '02' WHERE REFERENCE = 2 OR REFERENCE = 02; 
UPDATE BECOME_TUTOR SET REFERENCE = '03' WHERE REFERENCE = 3 OR REFERENCE = 03; 
UPDATE BECOME_TUTOR SET REFERENCE = '04' WHERE REFERENCE = 4 OR REFERENCE = 04; 
UPDATE BECOME_TUTOR SET REFERENCE = '05' WHERE REFERENCE = 5 OR REFERENCE = 05; 

UPDATE FIND_TUTOR SET REFERENCE = '01' WHERE REFERENCE = 1 OR REFERENCE = 01; 
UPDATE FIND_TUTOR SET REFERENCE = '02' WHERE REFERENCE = 2 OR REFERENCE = 02; 
UPDATE FIND_TUTOR SET REFERENCE = '03' WHERE REFERENCE = 3 OR REFERENCE = 03; 
UPDATE FIND_TUTOR SET REFERENCE = '04' WHERE REFERENCE = 4 OR REFERENCE = 04; 
UPDATE FIND_TUTOR SET REFERENCE = '05' WHERE REFERENCE = 5 OR REFERENCE = 05; 

UPDATE SUBSCRIBE_WITH_US SET REFERENCE = '01' WHERE REFERENCE = 1 OR REFERENCE = 01; 
UPDATE SUBSCRIBE_WITH_US SET REFERENCE = '02' WHERE REFERENCE = 2 OR REFERENCE = 02; 
UPDATE SUBSCRIBE_WITH_US SET REFERENCE = '03' WHERE REFERENCE = 3 OR REFERENCE = 03; 
UPDATE SUBSCRIBE_WITH_US SET REFERENCE = '04' WHERE REFERENCE = 4 OR REFERENCE = 04; 
UPDATE SUBSCRIBE_WITH_US SET REFERENCE = '05' WHERE REFERENCE = 5 OR REFERENCE = 05; 

COMMIT;

UPDATE PREFERRED_TEACHING_TYPE_LOOKUP SET VALUE = '01' WHERE VALUE = 1 OR VALUE = 01; 
UPDATE PREFERRED_TEACHING_TYPE_LOOKUP SET VALUE = '02' WHERE VALUE = 2 OR VALUE = 02; 
UPDATE PREFERRED_TEACHING_TYPE_LOOKUP SET VALUE = '03' WHERE VALUE = 3 OR VALUE = 03; 

UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '01' WHERE PREFERRED_TEACHING_TYPE = 1 OR PREFERRED_TEACHING_TYPE = 01; 
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '02' WHERE PREFERRED_TEACHING_TYPE = 2 OR PREFERRED_TEACHING_TYPE = 02; 
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '03' WHERE PREFERRED_TEACHING_TYPE = 3 OR PREFERRED_TEACHING_TYPE = 03; 
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '01;02' WHERE PREFERRED_TEACHING_TYPE = '1;2'; 
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '01;03' WHERE PREFERRED_TEACHING_TYPE = '1;3'; 
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '02;03' WHERE PREFERRED_TEACHING_TYPE = '2;3'; 
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '01;02;03' WHERE PREFERRED_TEACHING_TYPE = '1;2;3'; 

UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '01' WHERE PREFERRED_TEACHING_TYPE = 1 OR PREFERRED_TEACHING_TYPE = 01; 
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '02' WHERE PREFERRED_TEACHING_TYPE = 2 OR PREFERRED_TEACHING_TYPE = 02; 
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '03' WHERE PREFERRED_TEACHING_TYPE = 3 OR PREFERRED_TEACHING_TYPE = 03; 
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '01;02' WHERE PREFERRED_TEACHING_TYPE = '1;2'; 
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '01;03' WHERE PREFERRED_TEACHING_TYPE = '1;3'; 
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '02;03' WHERE PREFERRED_TEACHING_TYPE = '2;3'; 
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '01;02;03' WHERE PREFERRED_TEACHING_TYPE = '1;2;3'; 

COMMIT;

UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '01;02;03' WHERE TUTOR_ID IN (11,14,18,26,34);
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '01;02;03' WHERE TENTATIVE_TUTOR_ID IN (27,34,48,53,61);
UPDATE REGISTERED_TUTOR SET PREFERRED_TEACHING_TYPE = '01;03' WHERE TUTOR_ID = 24;
UPDATE BECOME_TUTOR SET PREFERRED_TEACHING_TYPE = '01;03' WHERE TENTATIVE_TUTOR_ID = 52;
-- Executed till here In Prod Do not write any more create new file