USE SEEK_MENTORE;

ALTER TABLE TUTOR_DOCUMENTS
ADD IS_APPROVED VARCHAR(2),
ADD WHO_ACTED VARCHAR(100),
ADD ACTION_DATE TIMESTAMP;

ALTER TABLE TUTOR_DOCUMENTS
ADD REMARKS VARCHAR(2000);
-- Executed till here In Prod Do not write any more create new file


