USE SEEK_MENTORE;

ALTER TABLE DEMO_TRACKER
ADD COLUMN DEMO_DATE_AND_TIME_MILLIS INT NOT NULL;

ALTER TABLE TUTOR_MAPPER
ADD COLUMN DEMO_DATE_AND_TIME_MILLIS INT NOT NULL;

ALTER TABLE TUTOR_MAPPER
DROP COLUMN DEMO_DATE_AND_TIME;

ALTER TABLE TUTOR_MAPPER
DROP COLUMN DEMO_DATE_AND_TIME_MILLIS;