USE SEEK_MENTORE;

CREATE TABLE EMAIL_TEMPLATE_LOOKUP(
VALUE VARCHAR(100) NOT NULL,
LABEL VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(100),
ORDER_OF_CATEGORY INT NOT NULL,
ORDER_IN_CATEGORY INT NOT NULL,
DESCRIPTION VARCHAR(500),
HIDDEN VARCHAR(2),
PRIMARY KEY (VALUE));

CREATE TABLE EMAIL_TEMPLATE(
EMAIL_TEMPLATE_ID INT NOT NULL AUTO_INCREMENT,
EMAIL_TEMPLATE_LOOKUP_VALUE VARCHAR(100) NOT NULL,
TO_ADDRESS VARCHAR(1000) NOT NULL,
CC_ADDRESS VARCHAR(1000),
BCC_ADDRESS VARCHAR(1000),
SUBJECT_CONTENT TEXT,
MESSAGE_CONTENT TEXT,
ADDED_BY VARCHAR(100) NOT NULL,
ADDED_MILLIS BIGINT NOT NULL,
LAST_UPDATED_BY VARCHAR(100) NOT NULL,
LAST_UPDATED_MILLIS BIGINT NOT NULL,
PRIMARY KEY (EMAIL_TEMPLATE_ID));