USE SEEK_MENTORE;

CREATE TABLE PACKAGE_ASSIGNMENT(
PACKAGE_ASSIGNMENT_ID INT NOT NULL AUTO_INCREMENT,
SUBSCRIPTION_PACKAGE_ID INT NOT NULL,
TOTAL_HOURS INT,
START_DATE_MILLIS BIGINT,
COMPLETED_HOURS INT,
COMPLETED_MINUTES INT,
END_DATE_MILLIS BIGINT,
WHO_ACTED VARCHAR(100),
ADMIN_REMARKS VARCHAR(2000),
CUSTOMER_REMARKS VARCHAR(2000),
TUTOR_REMARKS VARCHAR(2000),
ACTION_DATE_MILLIS BIGINT,
IS_CUSTOMER_GRIEVED VARCHAR(2),
IS_TUTOR_GRIEVED VARCHAR(2),
CUSTOMER_HAPPINESS_INDEX VARCHAR(2),
TUTOR_HAPPINESS_INDEX VARCHAR(2),
RECORD_LAST_UPDATED_MILLIS BIGINT,
UPDATED_BY VARCHAR(100),
PRIMARY KEY (PACKAGE_ASSIGNMENT_ID));

ALTER TABLE SUBSCRIPTION_PACKAGE
DROP COLUMN TOTAL_HOURS,
DROP COLUMN COMPLETED_HOURS,
DROP COLUMN COMPLETED_MINUTES;

ALTER TABLE PACKAGE_ASSIGNMENT
ADD CREATED_MILLIS BIGINT;

CREATE TABLE HAPPINESS_INDEX_LOOKUP(
VALUE VARCHAR(100) NOT NULL,
LABEL VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(100),
ORDER_OF_CATEGORY INT NOT NULL,
ORDER_IN_CATEGORY INT NOT NULL,
DESCRIPTION VARCHAR(500),
HIDDEN VARCHAR(2),
PRIMARY KEY (VALUE));

INSERT INTO HAPPINESS_INDEX_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION, HIDDEN) VALUES('01', 'Very Poor', NULL, 1, 1, NULL, NULL);
INSERT INTO HAPPINESS_INDEX_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION, HIDDEN) VALUES('02', 'Fair Enough', NULL, 1, 2, NULL, NULL);
INSERT INTO HAPPINESS_INDEX_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION, HIDDEN) VALUES('03', 'Good', NULL, 1, 3, NULL, NULL);
INSERT INTO HAPPINESS_INDEX_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION, HIDDEN) VALUES('04', 'Very Good', NULL, 1, 2, NULL, NULL);
INSERT INTO HAPPINESS_INDEX_LOOKUP(VALUE, LABEL, CATEGORY, ORDER_OF_CATEGORY, ORDER_IN_CATEGORY, DESCRIPTION, HIDDEN) VALUES('05', 'Superb', NULL, 1, 3, NULL, NULL);

ALTER TABLE SUBSCRIPTION_PACKAGE
ADD CREATED_MILLIS BIGINT;